### ISSUE TITLE
Is this the repo for Morningstar.com financial data?

### ISSUE THREAD

**Issue by datatalking** [omx/API-Docs#4]
We cannot access the API to get data, we get empty databases

**Comment by timothyquinn-morningstar** [comment]
No, this is the API for EAP.

**Comment by datatalking** [comment]
@timothyquinn-morningstar EAP as in not the free trial? We have API username and password but cannot find code to connect. Where would we find that?

**Comment by timothyquinn-morningstar** [comment]
No, this is EAP, a completely different product, unrelated to Morningstar financial data. You'll need to contact corporate IT for guidance on locating the APIs you require.
